# Generated by Django 5.0.7 on 2026-01-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
